name: Build

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Build react-emoji-textarea 😆💖
        run: npm ci && npm run build
      - name: Upload build folder (Chrome Extension)
        uses: actions/upload-artifact@v4
        with:
          name: lib
          path: dist/
          retention-days: 7
